export interface MembersInterface {
    memberId?:number,
    nom:string,
    prenoms:string,
    userName:string,
    password:string,
    role:string,
    location:string,
    phone:number,
    email:string,
    // status:string,
    memberPhotoUrl:string,
    dateJoined:Date,
    isActive:boolean,
}
